## Author  
**Kanishka Sharma**

* 🔗 LinkedIn - www.linkedin.com/in/kanishka2985


* 🤖 Github - https://github.com/kanishka2985

# Film Recommendation System

In [1]:
# Importing all the necesaary Librarires
import pandas as pd
import numpy as np
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [4]:
#Loading of dataset
path='Copy of Copy of movies.csv'
data=pd.read_csv(path)

In [5]:
# View of dataset
data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [6]:
# Count of Rows & Columns
data.shape

(4803, 24)

In [7]:
# Datset Information
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   index                 4803 non-null   int64  
 1   budget                4803 non-null   int64  
 2   genres                4775 non-null   object 
 3   homepage              1712 non-null   object 
 4   id                    4803 non-null   int64  
 5   keywords              4391 non-null   object 
 6   original_language     4803 non-null   object 
 7   original_title        4803 non-null   object 
 8   overview              4800 non-null   object 
 9   popularity            4803 non-null   float64
 10  production_companies  4803 non-null   object 
 11  production_countries  4803 non-null   object 
 12  release_date          4802 non-null   object 
 13  revenue               4803 non-null   int64  
 14  runtime               4801 non-null   float64
 15  spoken_languages     

In [8]:
# Selecting the needed features
features = ['genres','keywords','tagline','cast','director','overview']

In [9]:
#dealing with null values
for feature in features:
  data[feature] = data[feature].fillna('')

In [10]:
# Combining all new features in 'combine' column
data['combine'] = data['genres']+' '+data['keywords']+' '+data['tagline']+' '+data['cast']+' '+data['director']+ ' '+data['overview']

In [11]:
data['combine'].head()

0    Action Adventure Fantasy Science Fiction cultu...
1    Adventure Fantasy Action ocean drug abuse exot...
2    Action Adventure Crime spy based on novel secr...
3    Action Crime Drama Thriller dc comics crime fi...
4    Action Adventure Science Fiction based on nove...
Name: combine, dtype: object

In [12]:
# Convert the 'combine' text column into a TF‑IDF sparse matrix
vector = TfidfVectorizer()
f_vector = vector.fit_transform(data['combine'])
print(f_vector)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 307355 stored elements and shape (4803, 30592)>
  Coords	Values
  (0, 561)	0.05971816344971169
  (0, 703)	0.06846420517510078
  (0, 9754)	0.08513696797398294
  (0, 23977)	0.07941905576010944
  (0, 10023)	0.07960231361105431
  (0, 6601)	0.1498786462809525
  (0, 5279)	0.1549075340655008
  (0, 10796)	0.11095111375730655
  (0, 25413)	0.24369151759694266
  (0, 29469)	0.08637114089261566
  (0, 5592)	0.17322386697661618
  (0, 25232)	0.1336739112380023
  (0, 9065)	0.14505772980982928
  (0, 27118)	0.08328687324810813
  (0, 30121)	0.07272849549697494
  (0, 19410)	0.0318696249813729
  (0, 20039)	0.37747447361884223
  (0, 23619)	0.11047375838269538
  (0, 30145)	0.18243919685121024
  (0, 30543)	0.15064979633862852
  (0, 23578)	0.16802034155542864
  (0, 24802)	0.158925784923944
  (0, 29614)	0.15064979633862852
  (0, 25868)	0.11590870590502833
  (0, 15569)	0.171366691592621
  :	:
  (4802, 9588)	0.10415492266309316
  (4802, 21386)	0.0897551

In [13]:
# Compute pairwise cosine similarity between all TF‑IDF vectors(to find the similarity between  features)
similarity = cosine_similarity(f_vector)

In [14]:
print(similarity)

[[1.         0.05083168 0.0332947  ... 0.02749812 0.0304889  0.0072518 ]
 [0.05083168 1.         0.04356836 ... 0.05077045 0.03100979 0.01521198]
 [0.0332947  0.04356836 1.         ... 0.02646984 0.04751623 0.01372603]
 ...
 [0.02749812 0.05077045 0.02646984 ... 1.         0.03481447 0.03546821]
 [0.0304889  0.03100979 0.04751623 ... 0.03481447 1.         0.03098945]
 [0.0072518  0.01521198 0.01372603 ... 0.03546821 0.03098945 1.        ]]


In [15]:
similarity.shape

(4803, 4803)

In [16]:
# Take movie name input from the user
movie_name = input('Enter your favourite movie name :')

# Convert all movie titles from the dataset into a list
list_of_all_title = data['title'].tolist()

# Find close matches of the entered movie name from the list of titles
find_close_match = difflib.get_close_matches(movie_name, list_of_all_title)

# Pick the best matching movie title
close_match = find_close_match[0]

# Get the index of the matched movie in the dataset
index_of_movie = data[data.title == close_match]['index'].values[0]

# Get similarity scores (cosine similarity) for this movie with all other movies
similar_score = list(enumerate(similarity[index_of_movie]))

# Sort movies based on similarity scores in descending order
similar_score_sort = sorted(similar_score, key = lambda x:x[1], reverse = True)

# Print top 30 most similar movies
print('Movies suggested for you : \n')
for i in range(30):
    index = similar_score_sort[i][0]
    print(data['title'][index])


Movies suggested for you : 

Avatar
Lifeforce
Moonraker
Alien
Star Trek Beyond
Gattaca
Aliens
Guardians of the Galaxy
Gravity
Lockout
Apollo 18
Lost in Space
Cargo
Lara Croft Tomb Raider: The Cradle of Life
Treasure Planet
Men in Black
Star Trek Into Darkness
Zathura: A Space Adventure
The Book of Life
Sunshine
Men in Black II
Space Chimps
The Helix... Loaded
Starship Troopers
Deep Impact
Tears of the Sun
The Right Stuff
Sphere
Terminator Salvation
Mad Max Beyond Thunderdome


In [19]:
import joblib

# Save the Film Recommendation Model
joblib.dump(similarity, 'film_recommendation_model.pkl')

['film_recommendation_model.pkl']